apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-subscriber
  labels:
    app: event-subscriber
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event-subscriber
  template:
    metadata:
      labels:
        app: event-subscriber
      annotations:
        dapr.io/enabled: "true"
        dapr.io/id: "event-subscriber"
        dapr.io/port: "50001"
        dapr.io/protocol: "grpc"
        dapr.io/config: "tracing"
    spec:
      containers:
      - name: user-container
        image: mchmarny/dapr-grpc-event-subscriber-template:latest
        ports:
        - containerPort: 50001
        env:
        - name: ADDRESS
          value: ":50001"
